name: CI
on: [push]
jobs:
  eslint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
        
      - name: checkout node version
        run: node --version
      
      - name: Install packages
        run: yarn 
      
      - name: Run ESlint
        run: yarn lint
        
  client:
    name: client code checkout
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'

      - name: checkout node version
        run: node --version
      
      - name: Install packages
        run: yarn --cwd ./client 

      - name: Run build
        run: yarn --cwd ./client build



